---
version: "2"
prepare:
  fetch:
    - url: "https://raw.githubusercontent.com/leticiaoliveira5/code-style/master/.rubocop.yml"
      path: ".rubocop.yml"
plugins:
  duplication:
    enabled: true
  rubocop:
    enabled: true
    channel: "rubocop-1-9-1" # https://github.com/codeclimate/codeclimate-rubocop/branches/all
    config:
      file: ".rubocop.yml"
  reek:
    enabled: true
    checks:
      IrresponsibleModule:
        enabled: false
  csslint:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
- config/
- vendor/
- bin/
- app/assets/javascripts/



