version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    depends_on:
      - db
    build: .
    command: bundle exec rails s -p ${PORT} -b '0.0.0.0'
    container_name: jobs_app
    volumes:
      - .:/jobs
    ports:
      - "${PORT}:${PORT}"
