version: '2'
services:
  web:
      build: .
      command: bundle exec rails s -p 3000 -b '0.0.0.0'
      container_name: jobs_app
      volumes:
          - .:/jobs
      ports:
          - "3000:3000"
